sudo: required
language: java
services:
  - docker
jdk:
  - oraclejdk8
script:
  - cp Dockerfile build/libs/Dockerfile
  - cp application.properties build/libs/application.properties
  - cd build/libs
  - docker build -t spring-auth-api-example .
