sudo: required
language: java
services:
- docker
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_c7f6ac455592_key -iv $encrypted_c7f6ac455592_iv
  -in gcloud-credentials.json.enc -out gcloud-credentials.json -d
- gcloud auth activate-service-account --key-file gcloud-credentials.json
script:
- cp Dockerfile build/libs/Dockerfile
- cp application.properties build/libs/application.properties
- cd build/libs
- docker build -t jbatista/spring-auth-api-example .
- docker tag jbatista/spring-auth-api-example gcr.io/spring-auth-api-project/spring-auth-api-example
- gcloud config set project 'spring-auth-api-project'
- gcloud docker -- push gcr.io/spring-auth-api-project/spring-auth-api-example

