sudo: required
language: java
services:
- docker
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_70489a482a02_key -iv $encrypted_70489a482a02_iv
  -in gcloud-credentials.json.enc -out gcloud-credentials.json -d
- sudo gcloud components install kubectl
- gcloud auth activate-service-account --key-file gcloud-credentials.json
- gcloud config set project 'spring-auth-api-project'
- gcloud container clusters get-credentials spring-auth-api-cluster --zone us-east1-d --project spring-auth-api-project
- 
script:
- cp Dockerfile build/libs/Dockerfile
- cp application.properties build/libs/application.properties
- cd build/libs
- docker build -t jbatista/spring-auth-api-example .
- docker tag jbatista/spring-auth-api-example gcr.io/spring-auth-api-project/spring-auth-api-example
- gcloud docker -- push gcr.io/spring-auth-api-project/spring-auth-api-example
- kubectl run web-node --image=gcr.io/spring-auth-api-project/spring-auth-api-example --port=8080
