sudo: required
language: java
services:
- docker
jdk:
- oraclejdk8
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
env:
  global:
  - PATH="${PATH}:${HOME}/google-cloud-sdk/bin"
  - PROJECT_NAME='spring-auth-api'
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - GCHOME=$HOME/google-cloud-sdk/bin
before_install:
- openssl aes-256-cbc -K $encrypted_70489a482a02_key -iv $encrypted_70489a482a02_iv
  -in gcloud-credentials.json.enc -out gcloud-credentials.json -d
- if [ ! -d "${HOME}/google-cloud-sdk" ]; then
    curl https://sdk.cloud.google.com | bash;
  fi
- $GCHOME/gcloud.sh version
- $GCHOME/gcloud.sh components install kubectl -q
- $GCHOME/gcloud.sh auth activate-service-account --key-file gcloud-credentials.json
- $GCHOME/gcloud.sh config set project "${PROJECT_NAME}-project"
- $GCHOME/gcloud.sh container clusters get-credentials spring-auth-api-cluster --zone us-east1-d --project "${PROJECT_NAME}-project"
script:
- cp Dockerfile build/libs/Dockerfile
- cp application.properties build/libs/application.properties
- cd build/libs
- docker build -t jbatista/spring-auth-api-example .
- docker tag "jbatista/${PROJECT_NAME}-example gcr.io/${PROJECT_NAME}-project/${PROJECT_NAME}-example"
- $GCHOME/gcloud.sh docker -- push "gcr.io/${PROJECT_NAME}-project/${PROJECT_NAME}-example"
- $GCHOME/kubectl.sh run web-node --image="gcr.io/${PROJECT_NAME}-project/${PROJECT_NAME}-example" --port=80
